<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TaskbarLyrics.Windows</RootNamespace>
    <AssemblyName>TaskbarLyrics.Windows</AssemblyName>
    <UseWPF>false</UseWPF>
  </PropertyGroup>

</Project>
