<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TaskbarLyrics.Cache</RootNamespace>
    <AssemblyName>TaskbarLyrics.Cache</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskbarLyrics.Core\TaskbarLyrics.Core.csproj" />
    <ProjectReference Include="..\TaskbarLyrics.QQMusic\TaskbarLyrics.QQMusic.csproj" />
  </ItemGroup>

</Project>
